import Flux2Core
import DiffusionCore

/// FLUX.2's sigma schedule — the architecture-owned schedule the core engine asks for (see
/// `DiffusionArchitecture.sigmas`). It is generated by the SAME `FlowMatchEulerScheduler` the resident
/// `Flux2Pipeline` uses, so the streamed path denoises on a bit-identical curve (the 512 parity gate
/// depends on this). The schedule's empirical `mu` depends on BOTH the image sequence length and the
/// step count, which is exactly why a fixed-shift sampler cannot reproduce it.
public enum Flux2Sigmas {

    /// FLUX packs the VAE latent 2×2 after an 8× downscale, so the transformer sees `(W/16)·(H/16)`
    /// image tokens (512 px → 1024, 1024 px → 4096) — the `imageSeqLen` the mu calculation needs.
    public static func imageSeqLen(width: Int, height: Int) -> Int {
        (width / 16) * (height / 16)
    }

    /// The `steps + 1` sigma schedule (trailing 0 included) for a T2I run at this resolution.
    public static func schedule(width: Int, height: Int, steps: Int) -> [Float] {
        let scheduler = FlowMatchEulerScheduler(numTrainTimesteps: 1000, shift: 1.0)
        scheduler.setTimesteps(numInferenceSteps: steps,
                               imageSeqLen: imageSeqLen(width: width, height: height),
                               strength: 1.0)
        return scheduler.sigmas
    }

    /// Convenience for the `DiffusionArchitecture.sigmas(size:steps:sampler:)` override.
    public static func schedule(size: ImageSize, steps: Int) -> [Float] {
        schedule(width: size.width, height: size.height, steps: steps)
    }
}
